# Generated by Django 6.0.4 on 2026-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact US',
                'verbose_name_plural': 'Contact US',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='contact_con_name_4a801b_idx'), models.Index(fields=['email'], name='contact_con_email_453111_idx'), models.Index(fields=['phone'], name='contact_con_phone_059573_idx')],
            },
        ),
    ]
