# Generated by Django 6.0.4 on 2026-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['name'], name='portfolio_s_name_18dbc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['name'], name='portfolio_t_name_9d980b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, db_index=True, max_length=225, null=True, unique=True)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['name'], name='portfolio_p_name_7a1407_idx'), models.Index(fields=['slug'], name='portfolio_p_slug_e96b08_idx'), models.Index(fields=['link'], name='portfolio_p_link_0072c2_idx')],
            },
        ),
    ]
